w10d01/library/config/routes.rb
Rails.application.routes.draw do
  resources :publishers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # namespace :admin do
  #   resources :authors 
  # end
  
  
  # resources :authors
  # resources :books


  resources :authors do
    resources :books
  end
  
end

w10d01/library/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d01/library/app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

w10d01/library/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

w10d01/library/app/models/publisher.rb
class Publisher < ApplicationRecord
end

w10d01/library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/library/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
    render json: @authors
  end
end

w10d01/library/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    # give me all of the books
    # @books = Book.all

    # give me only the books for the specified author
    # a request looks like /authors/:author_id/books
    @author = Author.find(params[:author_id])
    @books = @author.books
  end
end

w10d01/library/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: %i[ show edit update destroy ]

  # GET /publishers or /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1 or /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers or /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: "Publisher was successfully created." }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1 or /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: "Publisher was successfully updated." }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1 or /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: "Publisher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publisher_params
      params.fetch(:publisher, {})
    end
end

w10d01/library/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/library/app/helpers/authors_helper.rb
module AuthorsHelper
end

w10d01/library/app/helpers/books_helper.rb
module BooksHelper
end

w10d01/library/app/helpers/publishers_helper.rb
module PublishersHelper
end

w10d01/library/app/views/authors/index.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Authors</title>
</head>
<body>
  <h1>All the Authors</h1>
  <% @authors.each do |author| %>
    <div>
      <h2><%= "#{author.first_name} #{author.last_name}" %> - <%= link_to 'Books', author_books_path(author)  %></h2>
    </div>
  <% end %>
</body>
</html>

w10d01/library/app/views/books/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Books</title>
</head>
<body>
  <h2>Books for <%= @author.first_name + ' ' + @author.last_name %></h2>
  <%= link_to 'Home', authors_path  %>
  <% @books.each do |book| %>
    <div>
      <%= book.title %>
    </div>
  <% end %>
</body>
</html>

w10d01/library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

w10d01/library/app/views/publishers/_form.html.erb
<%= form_with(model: publisher) do |form| %>
  <% if publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
        <% publisher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w10d01/library/app/views/publishers/edit.html.erb
<h1>Editing Publisher</h1>

<%= render 'form', publisher: @publisher %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

w10d01/library/app/views/publishers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publishers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= link_to 'Show', publisher %></td>
        <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
        <td><%= link_to 'Destroy', publisher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publisher', new_publisher_path %>

w10d01/library/app/views/publishers/new.html.erb
<h1>New Publisher</h1>

<%= render 'form', publisher: @publisher %>

<%= link_to 'Back', publishers_path %>

w10d01/library/app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>